# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.srcs/sources_1/ip/sdp_w4096x2_r4096x2/sdp_w4096x2_r4096x2.xci
# IP: The module: 'sdp_w4096x2_r4096x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/ip/sdp_w4096x2_r4096x2/sdp_w4096x2_r4096x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdp_w4096x2_r4096x2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.srcs/sources_1/ip/sdp_w4096x2_r4096x2/sdp_w4096x2_r4096x2.xci
# IP: The module: 'sdp_w4096x2_r4096x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/ip/sdp_w4096x2_r4096x2/sdp_w4096x2_r4096x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdp_w4096x2_r4096x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
