# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.runs/synth_1/andromeda_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku5p-ffvb676-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.cache/wt [current_project]
set_property parent.project_path /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
set_property verilog_define PUZHI=1 [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/hdl/andromeda_wrapper.v
add_files /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.srcs/sources_1/bd/andromeda/andromeda.bd
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/par/andromeda_ddr4_0_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/bd_828f_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/bd_828f_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/bd_828f_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/bd_828f_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_2/bd_828f_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_3/bd_828f_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_6/bd_828f_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_9/bd_828f_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_10/bd_828f_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/bd_828f_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/andromeda_ddr4_0_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/andromeda_ddr4_0_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/andromeda_ddr4_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/par/andromeda_ddr4_0_0.xdc]
set_property used_in_synthesis false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ila_0_0/andromeda_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_microblaze_0_0/andromeda_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_microblaze_0_0/andromeda_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_microblaze_0_0/andromeda_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_uartlite_0_0/andromeda_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_uartlite_0_0/andromeda_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_uartlite_0_0/andromeda_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_timer_0_0/andromeda_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_timer_0_0/andromeda_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_dlmb_v10_0/andromeda_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ilmb_v10_0/andromeda_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_dlmb_bram_if_cntlr_0/andromeda_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ilmb_bram_if_cntlr_0/andromeda_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_lmb_bram_0/andromeda_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_rst_ddr4_0_333M_0/andromeda_rst_ddr4_0_333M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_rst_ddr4_0_333M_0/andromeda_rst_ddr4_0_333M_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_rst_ddr4_0_333M_0/andromeda_rst_ddr4_0_333M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_rst_ddr4_0_100M_0/andromeda_rst_ddr4_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_rst_ddr4_0_100M_0/andromeda_rst_ddr4_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_rst_ddr4_0_100M_0/andromeda_rst_ddr4_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_1/bd_98e1_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_1/bd_98e1_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_2/bd_98e1_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_2/bd_98e1_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_3/bd_98e1_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_3/bd_98e1_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_4/bd_98e1_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_5/bd_98e1_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_6/bd_98e1_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_7/bd_98e1_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_8/bd_98e1_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_12/bd_98e1_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_13/bd_98e1_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_14/bd_98e1_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_15/bd_98e1_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_16/bd_98e1_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_17/bd_98e1_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_21/bd_98e1_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_22/bd_98e1_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_23/bd_98e1_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_24/bd_98e1_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_25/bd_98e1_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_26/bd_98e1_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_30/bd_98e1_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_31/bd_98e1_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_32/bd_98e1_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_33/bd_98e1_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_34/bd_98e1_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_35/bd_98e1_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_36/bd_98e1_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_37/bd_98e1_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_38/bd_98e1_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_39/bd_98e1_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_41/bd_98e1_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_42/bd_98e1_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_43/bd_98e1_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_44/bd_98e1_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_45/bd_98e1_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_46/bd_98e1_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_48/bd_98e1_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_49/bd_98e1_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_50/bd_98e1_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_51/bd_98e1_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_52/bd_98e1_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_53/bd_98e1_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_55/bd_98e1_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_56/bd_98e1_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_57/bd_98e1_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_58/bd_98e1_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_59/bd_98e1_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_60/bd_98e1_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_62/bd_98e1_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_63/bd_98e1_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_64/bd_98e1_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_65/bd_98e1_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_66/bd_98e1_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_67/bd_98e1_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_axi_dpe_0_0/andromeda_axi_dpe_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_mdm_0_0/andromeda_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_mdm_0_0/andromeda_mdm_0_0_ooc_trace.xdc]
set_property used_in_synthesis false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/bd_85fa_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/bd_85fa_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/andromeda_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/andromeda_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/sw/calibration_0/Debug/calibration_ddr.elf]
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_microblaze_0_0/data/mb_bootloop_le.elf]

read_ip -quiet /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.srcs/sources_1/ip/sdp_w4096x2_r4096x2/sdp_w4096x2_r4096x2.xci
set_property used_in_implementation false [get_files -all /home/malik/andromeda_ila/andromeda/Vivado/puzhi/puzhi.gen/sources_1/ip/sdp_w4096x2_r4096x2/sdp_w4096x2_r4096x2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/malik/andromeda_ila/andromeda/Vivado/board_xdc/puzhi.xdc
set_property used_in_implementation false [get_files /home/malik/andromeda_ila/andromeda/Vivado/board_xdc/puzhi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top andromeda_wrapper -part xcku5p-ffvb676-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef andromeda_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file andromeda_wrapper_utilization_synth.rpt -pb andromeda_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
