# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ujaved/work_dir/axi_dpe_ila_v3.0/AXI-Dot-Product-Accelerator/Vivado/board_xdc/puzhi.xdc

# Block Designs: bd/andromeda/andromeda.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda || ORIG_REF_NAME==andromeda} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_ddr4_0_0/andromeda_ddr4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_ddr4_0_0 || ORIG_REF_NAME==andromeda_ddr4_0_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_ila_0_0/andromeda_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_ila_0_0 || ORIG_REF_NAME==andromeda_ila_0_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_util_vector_logic_0_0/andromeda_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_util_vector_logic_0_0 || ORIG_REF_NAME==andromeda_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_microblaze_0_0/andromeda_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_microblaze_0_0 || ORIG_REF_NAME==andromeda_microblaze_0_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_axi_uartlite_0_0/andromeda_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_axi_uartlite_0_0 || ORIG_REF_NAME==andromeda_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_sd_controller_wrapper_0_0/andromeda_sd_controller_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_sd_controller_wrapper_0_0 || ORIG_REF_NAME==andromeda_sd_controller_wrapper_0_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_axi_timer_0_0/andromeda_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_axi_timer_0_0 || ORIG_REF_NAME==andromeda_axi_timer_0_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_dlmb_v10_0/andromeda_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_dlmb_v10_0 || ORIG_REF_NAME==andromeda_dlmb_v10_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_ilmb_v10_0/andromeda_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_ilmb_v10_0 || ORIG_REF_NAME==andromeda_ilmb_v10_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_dlmb_bram_if_cntlr_0/andromeda_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==andromeda_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_ilmb_bram_if_cntlr_0/andromeda_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==andromeda_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_lmb_bram_0/andromeda_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_lmb_bram_0 || ORIG_REF_NAME==andromeda_lmb_bram_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_rst_ddr4_0_333M_0/andromeda_rst_ddr4_0_333M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_rst_ddr4_0_333M_0 || ORIG_REF_NAME==andromeda_rst_ddr4_0_333M_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_rst_ddr4_0_100M_0/andromeda_rst_ddr4_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_rst_ddr4_0_100M_0 || ORIG_REF_NAME==andromeda_rst_ddr4_0_100M_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_axi_smc_0/andromeda_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_axi_smc_0 || ORIG_REF_NAME==andromeda_axi_smc_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_axi_dpe_0_0/andromeda_axi_dpe_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_axi_dpe_0_0 || ORIG_REF_NAME==andromeda_axi_dpe_0_0} -quiet] -quiet

# IP: ip/floating_point_2/floating_point_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_2 || ORIG_REF_NAME==floating_point_2} -quiet] -quiet

# IP: ip/floating_point_1/floating_point_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1} -quiet] -quiet

# IP: ip/floating_point_3/floating_point_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_3 || ORIG_REF_NAME==floating_point_3} -quiet] -quiet

# IP: ip/floating_point_0/floating_point_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet

# IP: ip/sdp_w4096x2_r4096x2/sdp_w4096x2_r4096x2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sdp_w4096x2_r4096x2 || ORIG_REF_NAME==sdp_w4096x2_r4096x2} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_mdm_0_0/andromeda_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_mdm_0_0 || ORIG_REF_NAME==andromeda_mdm_0_0} -quiet] -quiet

# IP: bd/andromeda/ip/andromeda_system_ila_0_0/andromeda_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_system_ila_0_0 || ORIG_REF_NAME==andromeda_system_ila_0_0} -quiet] -quiet

# XDC: /home/ujaved/work_dir/axi_dpe_ila_v3.0/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/andromeda_ooc.xdc
