# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.srcs/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/andromeda_system_ila_0_0.xci
# IP: The module: 'andromeda_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/bd_85fa.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa || ORIG_REF_NAME==bd_85fa} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/bd_85fa_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_ila_lib_0 || ORIG_REF_NAME==bd_85fa_ila_lib_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_1/bd_85fa_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_g_inst_0 || ORIG_REF_NAME==bd_85fa_g_inst_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_2/bd_85fa_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_aw_0 || ORIG_REF_NAME==bd_85fa_slot_0_aw_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_3/bd_85fa_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_w_0 || ORIG_REF_NAME==bd_85fa_slot_0_w_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_4/bd_85fa_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_b_0 || ORIG_REF_NAME==bd_85fa_slot_0_b_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_5/bd_85fa_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_ar_0 || ORIG_REF_NAME==bd_85fa_slot_0_ar_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_6/bd_85fa_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_r_0 || ORIG_REF_NAME==bd_85fa_slot_0_r_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_7/bd_85fa_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_aw_0 || ORIG_REF_NAME==bd_85fa_slot_1_aw_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_8/bd_85fa_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_w_0 || ORIG_REF_NAME==bd_85fa_slot_1_w_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_9/bd_85fa_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_b_0 || ORIG_REF_NAME==bd_85fa_slot_1_b_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_10/bd_85fa_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_ar_0 || ORIG_REF_NAME==bd_85fa_slot_1_ar_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_11/bd_85fa_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_r_0 || ORIG_REF_NAME==bd_85fa_slot_1_r_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_12/bd_85fa_slot_2_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_aw_0 || ORIG_REF_NAME==bd_85fa_slot_2_aw_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_13/bd_85fa_slot_2_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_w_0 || ORIG_REF_NAME==bd_85fa_slot_2_w_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_14/bd_85fa_slot_2_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_b_0 || ORIG_REF_NAME==bd_85fa_slot_2_b_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_15/bd_85fa_slot_2_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_ar_0 || ORIG_REF_NAME==bd_85fa_slot_2_ar_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_16/bd_85fa_slot_2_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_r_0 || ORIG_REF_NAME==bd_85fa_slot_2_r_0} -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_85fa_ila_lib_0 || ORIG_REF_NAME==bd_85fa_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_85fa_ila_lib_0 || ORIG_REF_NAME==bd_85fa_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/bd_85fa_ila_lib_0_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/bd_85fa_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/andromeda_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'andromeda_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.srcs/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/andromeda_system_ila_0_0.xci
# IP: The module: 'andromeda_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/bd_85fa.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa || ORIG_REF_NAME==bd_85fa} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/bd_85fa_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_ila_lib_0 || ORIG_REF_NAME==bd_85fa_ila_lib_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_1/bd_85fa_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_g_inst_0 || ORIG_REF_NAME==bd_85fa_g_inst_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_2/bd_85fa_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_aw_0 || ORIG_REF_NAME==bd_85fa_slot_0_aw_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_3/bd_85fa_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_w_0 || ORIG_REF_NAME==bd_85fa_slot_0_w_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_4/bd_85fa_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_b_0 || ORIG_REF_NAME==bd_85fa_slot_0_b_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_5/bd_85fa_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_ar_0 || ORIG_REF_NAME==bd_85fa_slot_0_ar_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_6/bd_85fa_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_0_r_0 || ORIG_REF_NAME==bd_85fa_slot_0_r_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_7/bd_85fa_slot_1_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_aw_0 || ORIG_REF_NAME==bd_85fa_slot_1_aw_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_8/bd_85fa_slot_1_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_w_0 || ORIG_REF_NAME==bd_85fa_slot_1_w_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_9/bd_85fa_slot_1_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_b_0 || ORIG_REF_NAME==bd_85fa_slot_1_b_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_10/bd_85fa_slot_1_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_ar_0 || ORIG_REF_NAME==bd_85fa_slot_1_ar_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_11/bd_85fa_slot_1_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_1_r_0 || ORIG_REF_NAME==bd_85fa_slot_1_r_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_12/bd_85fa_slot_2_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_aw_0 || ORIG_REF_NAME==bd_85fa_slot_2_aw_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_13/bd_85fa_slot_2_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_w_0 || ORIG_REF_NAME==bd_85fa_slot_2_w_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_14/bd_85fa_slot_2_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_b_0 || ORIG_REF_NAME==bd_85fa_slot_2_b_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_15/bd_85fa_slot_2_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_ar_0 || ORIG_REF_NAME==bd_85fa_slot_2_ar_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_16/bd_85fa_slot_2_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85fa_slot_2_r_0 || ORIG_REF_NAME==bd_85fa_slot_2_r_0} -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_85fa_ila_lib_0 || ORIG_REF_NAME==bd_85fa_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_85fa_ila_lib_0 || ORIG_REF_NAME==bd_85fa_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/bd_85fa_ila_lib_0_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/bd_85fa_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_system_ila_0_0/andromeda_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'andromeda_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
