# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/malik/andromeda_ila/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.srcs/sources_1/bd/andromeda/ip/andromeda_dlmb_v10_0/andromeda_dlmb_v10_0.xci
# IP: The module: 'andromeda_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/malik/andromeda_ila/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_dlmb_v10_0/andromeda_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'andromeda_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.srcs/sources_1/bd/andromeda/ip/andromeda_dlmb_v10_0/andromeda_dlmb_v10_0.xci
# IP: The module: 'andromeda_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/malik/andromeda_ila/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_dlmb_v10_0/andromeda_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'andromeda_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
