domain_path: /home/ujaved/work_dir/axi_dpe_ila_v3.0/AXI-Dot-Product-Accelerator/Vitis/puzhi_workspace/puzhi_mb_platform/export/puzhi_mb_platform/sw/standalone_microblaze_0
app_src_dir: /opt/tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
