#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 12 09:28:27 UTC 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_axi_dpe_behav -key {Behavioral:sim_1:Functional:tb_axi_dpe} -tclbatch tb_axi_dpe.tcl -protoinst "protoinst_files/bd_828f.protoinst" -protoinst "protoinst_files/bd_98e1.protoinst" -protoinst "protoinst_files/bd_85fa.protoinst" -protoinst "protoinst_files/andromeda.protoinst" -log simulate.log"
xsim tb_axi_dpe_behav -key {Behavioral:sim_1:Functional:tb_axi_dpe} -tclbatch tb_axi_dpe.tcl -protoinst "protoinst_files/bd_828f.protoinst" -protoinst "protoinst_files/bd_98e1.protoinst" -protoinst "protoinst_files/bd_85fa.protoinst" -protoinst "protoinst_files/andromeda.protoinst" -log simulate.log

