transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/microblaze_v11_0_14
vlib riviera/xil_defaultlib
vlib riviera/lib_cdc_v1_0_3
vlib riviera/proc_sys_reset_v5_0_16
vlib riviera/lmb_v10_v3_0_14
vlib riviera/lmb_bram_if_cntlr_v4_0_25
vlib riviera/blk_mem_gen_v8_4_9
vlib riviera/iomodule_v3_1_11
vlib riviera/util_vector_logic_v2_0_4
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/lib_pkg_v1_0_4
vlib riviera/lib_srl_fifo_v1_0_4
vlib riviera/axi_uartlite_v2_0_37
vlib riviera/axi_timer_v2_0_35
vlib riviera/xlconstant_v1_1_9
vlib riviera/smartconnect_v1_0
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_register_slice_v2_1_33
vlib riviera/axi_vip_v1_1_19
vlib riviera/mdm_v3_2_27
vlib riviera/gigantic_mux
vlib riviera/xlconcat_v2_1_6

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap microblaze_v11_0_14 riviera/microblaze_v11_0_14
vmap xil_defaultlib riviera/xil_defaultlib
vmap lib_cdc_v1_0_3 riviera/lib_cdc_v1_0_3
vmap proc_sys_reset_v5_0_16 riviera/proc_sys_reset_v5_0_16
vmap lmb_v10_v3_0_14 riviera/lmb_v10_v3_0_14
vmap lmb_bram_if_cntlr_v4_0_25 riviera/lmb_bram_if_cntlr_v4_0_25
vmap blk_mem_gen_v8_4_9 riviera/blk_mem_gen_v8_4_9
vmap iomodule_v3_1_11 riviera/iomodule_v3_1_11
vmap util_vector_logic_v2_0_4 riviera/util_vector_logic_v2_0_4
vmap axi_lite_ipif_v3_0_4 riviera/axi_lite_ipif_v3_0_4
vmap lib_pkg_v1_0_4 riviera/lib_pkg_v1_0_4
vmap lib_srl_fifo_v1_0_4 riviera/lib_srl_fifo_v1_0_4
vmap axi_uartlite_v2_0_37 riviera/axi_uartlite_v2_0_37
vmap axi_timer_v2_0_35 riviera/axi_timer_v2_0_35
vmap xlconstant_v1_1_9 riviera/xlconstant_v1_1_9
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_33 riviera/axi_register_slice_v2_1_33
vmap axi_vip_v1_1_19 riviera/axi_vip_v1_1_19
vmap mdm_v3_2_27 riviera/mdm_v3_2_27
vmap gigantic_mux riviera/gigantic_mux
vmap xlconcat_v2_1_6 riviera/xlconcat_v2_1_6

vlog -work xilinx_vip  -incr "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"/opt/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/opt/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"/opt/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work microblaze_v11_0_14 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/a243/hdl/microblaze_v11_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/sim/bd_828f_microblaze_I_0.vhd" \

vcom -work lib_cdc_v1_0_3 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_16 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/sim/bd_828f_rst_0_0.vhd" \

vcom -work lmb_v10_v3_0_14 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/7495/hdl/lmb_v10_v3_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_2/sim/bd_828f_ilmb_0.vhd" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_3/sim/bd_828f_dlmb_0.vhd" \

vcom -work lmb_bram_if_cntlr_v4_0_25 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/73e9/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_4/sim/bd_828f_dlmb_cntlr_0.vhd" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_5/sim/bd_828f_ilmb_cntlr_0.vhd" \

vlog -work blk_mem_gen_v8_4_9  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/5ec1/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_6/sim/bd_828f_lmb_bram_I_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_7/sim/bd_828f_second_dlmb_cntlr_0.vhd" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_8/sim/bd_828f_second_ilmb_cntlr_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_9/sim/bd_828f_second_lmb_bram_I_0.v" \

vcom -work iomodule_v3_1_11 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/76e9/hdl/iomodule_v3_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_10/sim/bd_828f_iomodule_0_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/sim/bd_828f.v" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/sim/andromeda_ddr4_0_0_microblaze_mcs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/phy/andromeda_ddr4_0_0_phy_ddr4.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy_behav.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob_byte.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/clocking/ddr4_phy_v2_2_pll.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_tristate_wrapper.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_riuor_wrapper.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_control_wrapper.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_byte_wrapper.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_bitslice_wrapper.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/ip_top/andromeda_ddr4_0_0_phy.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_wtr.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ref.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_rd_wr.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_periodic.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_group.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_merge_enc.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_gen.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_fi_xor.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_dec_fix.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_buf.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ctl.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_c.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_ap.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_p.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_mux_p.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_c.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_a.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_timer.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_rank.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/controller/ddr4_v2_2_mc.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_wr_data.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_rd_data.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_cmd.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ui/ddr4_v2_2_ui.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_ar_channel.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_aw_channel.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_b_channel.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_arbiter.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_fsm.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_translator.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_fifo.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_incr_cmd.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_r_channel.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_w_channel.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wr_cmd_fsm.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wrap_cmd.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_a_upsizer.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_register_slice.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_upsizer.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_axic_register_slice.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_and.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_and.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_or.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_or.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_command_fifo.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel_static.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_r_upsizer.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi/ddr4_v2_2_w_upsizer.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_addr_decode.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_read.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg_bank.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_top.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_write.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/clocking/ddr4_v2_2_infrastructure.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_bram.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_write.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_byte.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_bit.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_sync.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_read.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_rd_en.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_pi.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_mc_odt.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_debug_microblaze.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx_data.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_config_rom.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_addr_decode.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_top.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_arbiter.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_cal.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_chipscope_xsdb_slave.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/ddr4_v2_2_dp_AB9.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top/andromeda_ddr4_0_0_ddr4.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top/andromeda_ddr4_0_0_ddr4_mem_intfc.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal/andromeda_ddr4_0_0_ddr4_cal_riu.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top/andromeda_ddr4_0_0.sv" \
"../../../bd/andromeda/ip/andromeda_ddr4_0_0/tb/andromeda_ddr4_0_0_microblaze_mcs_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_ila_0_0/sim/andromeda_ila_0_0.v" \

vlog -work util_vector_logic_v2_0_4  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/fd7b/hdl/util_vector_logic_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_util_vector_logic_0_0/sim/andromeda_util_vector_logic_0_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_microblaze_0_0/sim/andromeda_microblaze_0_0.vhd" \

vcom -work axi_lite_ipif_v3_0_4 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_pkg_v1_0_4 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_4 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_uartlite_v2_0_37 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/9a87/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_axi_uartlite_0_0/sim/andromeda_axi_uartlite_0_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_sd_controller_wrapper_0_0/sim/andromeda_sd_controller_wrapper_0_0.v" \

vcom -work axi_timer_v2_0_35 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/906c/hdl/axi_timer_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_axi_timer_0_0/sim/andromeda_axi_timer_0_0.vhd" \
"../../../bd/andromeda/ip/andromeda_dlmb_v10_0/sim/andromeda_dlmb_v10_0.vhd" \
"../../../bd/andromeda/ip/andromeda_ilmb_v10_0/sim/andromeda_ilmb_v10_0.vhd" \
"../../../bd/andromeda/ip/andromeda_dlmb_bram_if_cntlr_0/sim/andromeda_dlmb_bram_if_cntlr_0.vhd" \
"../../../bd/andromeda/ip/andromeda_ilmb_bram_if_cntlr_0/sim/andromeda_ilmb_bram_if_cntlr_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_lmb_bram_0/sim/andromeda_lmb_bram_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_rst_ddr4_0_333M_0/sim/andromeda_rst_ddr4_0_333M_0.vhd" \
"../../../bd/andromeda/ip/andromeda_rst_ddr4_0_100M_0/sim/andromeda_rst_ddr4_0_100M_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/sim/bd_98e1.v" \

vlog -work xlconstant_v1_1_9  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_0/sim/bd_98e1_one_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_1/sim/bd_98e1_psr0_0.vhd" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_2/sim/bd_98e1_psr_aclk_0.vhd" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_3/sim/bd_98e1_psr_aclk1_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_4/sim/bd_98e1_arsw_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_5/sim/bd_98e1_rsw_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_6/sim/bd_98e1_awsw_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_7/sim/bd_98e1_wsw_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_8/sim/bd_98e1_bsw_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f49a/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_9/sim/bd_98e1_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_10/sim/bd_98e1_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/63ed/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_11/sim/bd_98e1_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_12/sim/bd_98e1_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_13/sim/bd_98e1_sarn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_14/sim/bd_98e1_srn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_15/sim/bd_98e1_sawn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_16/sim/bd_98e1_swn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_17/sim/bd_98e1_sbn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_18/sim/bd_98e1_s01mmu_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_19/sim/bd_98e1_s01tr_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_20/sim/bd_98e1_s01sic_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_21/sim/bd_98e1_s01a2s_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_22/sim/bd_98e1_sarn_1.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_23/sim/bd_98e1_srn_1.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_24/sim/bd_98e1_sawn_1.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_25/sim/bd_98e1_swn_1.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_26/sim/bd_98e1_sbn_1.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_27/sim/bd_98e1_s02mmu_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_28/sim/bd_98e1_s02tr_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_29/sim/bd_98e1_s02sic_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_30/sim/bd_98e1_s02a2s_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_31/sim/bd_98e1_sawn_2.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_32/sim/bd_98e1_swn_2.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_33/sim/bd_98e1_sbn_2.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_34/sim/bd_98e1_m00s2a_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_35/sim/bd_98e1_m00arn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_36/sim/bd_98e1_m00rn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_37/sim/bd_98e1_m00awn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_38/sim/bd_98e1_m00wn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_39/sim/bd_98e1_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/37bc/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_40/sim/bd_98e1_m00e_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_41/sim/bd_98e1_m01s2a_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_42/sim/bd_98e1_m01arn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_43/sim/bd_98e1_m01rn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_44/sim/bd_98e1_m01awn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_45/sim/bd_98e1_m01wn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_46/sim/bd_98e1_m01bn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_47/sim/bd_98e1_m01e_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_48/sim/bd_98e1_m02s2a_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_49/sim/bd_98e1_m02arn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_50/sim/bd_98e1_m02rn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_51/sim/bd_98e1_m02awn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_52/sim/bd_98e1_m02wn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_53/sim/bd_98e1_m02bn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_54/sim/bd_98e1_m02e_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_55/sim/bd_98e1_m03s2a_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_56/sim/bd_98e1_m03arn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_57/sim/bd_98e1_m03rn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_58/sim/bd_98e1_m03awn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_59/sim/bd_98e1_m03wn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_60/sim/bd_98e1_m03bn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_61/sim/bd_98e1_m03e_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_62/sim/bd_98e1_m04s2a_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_63/sim/bd_98e1_m04arn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_64/sim/bd_98e1_m04rn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_65/sim/bd_98e1_m04awn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_66/sim/bd_98e1_m04wn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_67/sim/bd_98e1_m04bn_0.sv" \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/bd_0/ip/ip_68/sim/bd_98e1_m04e_0.sv" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_33  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_19  -incr "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_axi_smc_0/sim/andromeda_axi_smc_0.v" \
"../../../bd/andromeda/ip/andromeda_axi_dpe_0_0/sim/andromeda_axi_dpe_0_0.v" \

vcom -work mdm_v3_2_27 -93  -incr \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/da3a/hdl/mdm_v3_2_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/andromeda/ip/andromeda_mdm_0_0/sim/andromeda_mdm_0_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/sim/bd_85fa.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_0/sim/bd_85fa_ila_lib_0.v" \

vlog -work gigantic_mux  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/96a0/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_1/bd_85fa_g_inst_0_gigantic_mux.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_1/sim/bd_85fa_g_inst_0.v" \

vlog -work xlconcat_v2_1_6  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/f0b6/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/0127/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/ec67/hdl" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/ip_top" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/rtl/cal" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/814a/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/1017/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/52c0/hdl/verilog" "+incdir+../../../../puzhi.gen/sources_1/bd/andromeda/ipshared/2276/hdl/verilog" "+incdir+/opt/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_14 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_16 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_25 -l blk_mem_gen_v8_4_9 -l iomodule_v3_1_11 -l util_vector_logic_v2_0_4 -l axi_lite_ipif_v3_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l axi_uartlite_v2_0_37 -l axi_timer_v2_0_35 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_33 -l axi_vip_v1_1_19 -l mdm_v3_2_27 -l gigantic_mux -l xlconcat_v2_1_6 \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_2/sim/bd_85fa_slot_0_aw_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_3/sim/bd_85fa_slot_0_w_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_4/sim/bd_85fa_slot_0_b_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_5/sim/bd_85fa_slot_0_ar_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_6/sim/bd_85fa_slot_0_r_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_7/sim/bd_85fa_slot_1_aw_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_8/sim/bd_85fa_slot_1_w_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_9/sim/bd_85fa_slot_1_b_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_10/sim/bd_85fa_slot_1_ar_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_11/sim/bd_85fa_slot_1_r_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_12/sim/bd_85fa_slot_2_aw_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_13/sim/bd_85fa_slot_2_w_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_14/sim/bd_85fa_slot_2_b_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_15/sim/bd_85fa_slot_2_ar_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/bd_0/ip/ip_16/sim/bd_85fa_slot_2_r_0.v" \
"../../../bd/andromeda/ip/andromeda_system_ila_0_0/sim/andromeda_system_ila_0_0.v" \
"../../../bd/andromeda/sim/andromeda.v" \

vlog -work xil_defaultlib \
"glbl.v"

