# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.srcs/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/andromeda_ddr4_0_0.xci
# IP: The module: 'andromeda_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/andromeda_ddr4_0_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_ddr4_0_0_phy || ORIG_REF_NAME==andromeda_ddr4_0_0_phy} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/andromeda_ddr4_0_0_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==andromeda_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/bd_828f.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f || ORIG_REF_NAME==bd_828f} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/bd_828f_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_microblaze_I_0 || ORIG_REF_NAME==bd_828f_microblaze_I_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/bd_828f_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_rst_0_0 || ORIG_REF_NAME==bd_828f_rst_0_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_2/bd_828f_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_ilmb_0 || ORIG_REF_NAME==bd_828f_ilmb_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_3/bd_828f_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_dlmb_0 || ORIG_REF_NAME==bd_828f_dlmb_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_4/bd_828f_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_828f_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_5/bd_828f_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_828f_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_6/bd_828f_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_lmb_bram_I_0 || ORIG_REF_NAME==bd_828f_lmb_bram_I_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_7/bd_828f_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_828f_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_8/bd_828f_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_828f_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_9/bd_828f_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_828f_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_10/bd_828f_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_iomodule_0_0 || ORIG_REF_NAME==bd_828f_iomodule_0_0} -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/par/andromeda_ddr4_0_0_phy_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/bd_828f_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_microblaze_I_0 || ORIG_REF_NAME==bd_828f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/bd_828f_microblaze_I_0_ooc_debug.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/bd_828f_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_rst_0_0 || ORIG_REF_NAME==bd_828f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/bd_828f_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_rst_0_0 || ORIG_REF_NAME==bd_828f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_2/bd_828f_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_ilmb_0 || ORIG_REF_NAME==bd_828f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_3/bd_828f_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_dlmb_0 || ORIG_REF_NAME==bd_828f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_6/bd_828f_lmb_bram_I_0_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_9/bd_828f_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_10/bd_828f_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_iomodule_0_0 || ORIG_REF_NAME==bd_828f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/bd_828f_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/andromeda_ddr4_0_0_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==andromeda_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==andromeda_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/andromeda_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/andromeda_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'andromeda_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/par/andromeda_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'andromeda_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.srcs/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/andromeda_ddr4_0_0.xci
# IP: The module: 'andromeda_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/andromeda_ddr4_0_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_ddr4_0_0_phy || ORIG_REF_NAME==andromeda_ddr4_0_0_phy} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/andromeda_ddr4_0_0_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==andromeda_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==andromeda_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/bd_828f.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f || ORIG_REF_NAME==bd_828f} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/bd_828f_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_microblaze_I_0 || ORIG_REF_NAME==bd_828f_microblaze_I_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/bd_828f_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_rst_0_0 || ORIG_REF_NAME==bd_828f_rst_0_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_2/bd_828f_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_ilmb_0 || ORIG_REF_NAME==bd_828f_ilmb_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_3/bd_828f_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_dlmb_0 || ORIG_REF_NAME==bd_828f_dlmb_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_4/bd_828f_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_828f_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_5/bd_828f_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_828f_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_6/bd_828f_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_lmb_bram_I_0 || ORIG_REF_NAME==bd_828f_lmb_bram_I_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_7/bd_828f_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_828f_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_8/bd_828f_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_828f_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_9/bd_828f_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_828f_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_10/bd_828f_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_828f_iomodule_0_0 || ORIG_REF_NAME==bd_828f_iomodule_0_0} -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_1/par/andromeda_ddr4_0_0_phy_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/bd_828f_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_microblaze_I_0 || ORIG_REF_NAME==bd_828f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_0/bd_828f_microblaze_I_0_ooc_debug.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/bd_828f_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_rst_0_0 || ORIG_REF_NAME==bd_828f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_1/bd_828f_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_rst_0_0 || ORIG_REF_NAME==bd_828f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_2/bd_828f_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_ilmb_0 || ORIG_REF_NAME==bd_828f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_3/bd_828f_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_dlmb_0 || ORIG_REF_NAME==bd_828f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_6/bd_828f_lmb_bram_I_0_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_9/bd_828f_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/ip/ip_10/bd_828f_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_828f_iomodule_0_0 || ORIG_REF_NAME==bd_828f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/bd_0/bd_828f_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/andromeda_ddr4_0_0_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==andromeda_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==andromeda_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/ip_0/andromeda_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/andromeda_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'andromeda_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/malik/andromeda_ila/AXI-DPE-simulation/AXI-Dot-Product-Accelerator/Vivado/puzhi/puzhi.gen/sources_1/bd/andromeda/ip/andromeda_ddr4_0_0/par/andromeda_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'andromeda_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
