#ifndef XMEM_CONFIG_H_
#define XMEM_CONFIG_H_

#define XPAR_DDR4_0_BASEADDRESS 0x80000000
#define XPAR_DDR4_0_HIGHADDRESS 0xffffffff
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x1ffff

#endif