set_property SRC_FILE_INFO {cfile:/home/malik/andromeda_ila/AXI-Dot-Product-Accelerator/Vivado/board_xdc/puzhi.xdc rfile:../../../../board_xdc/puzhi.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22 [get_ports c0_sys_clk_p]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports c0_sys_clk_n]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD14 [get_ports sys_rstn]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H23 [get_ports {c0_ddr4_cs_n[0]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G24 [get_ports {c0_ddr4_ck_t[0]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25 [get_ports {c0_ddr4_ck_c[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H24 [get_ports {c0_ddr4_cke[0]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L25 [get_ports c0_ddr4_reset_n]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L24 [get_ports c0_ddr4_act_n]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H21 [get_ports {c0_ddr4_ba[1]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J25 [get_ports {c0_ddr4_ba[0]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M24 [get_ports {c0_ddr4_odt[0]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G26 [get_ports {c0_ddr4_bg[0]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F23 [get_ports {c0_ddr4_adr[0]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25 [get_ports {c0_ddr4_adr[1]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D23 [get_ports {c0_ddr4_adr[2]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B26 [get_ports {c0_ddr4_adr[3]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E23 [get_ports {c0_ddr4_adr[4]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C26 [get_ports {c0_ddr4_adr[5]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F24 [get_ports {c0_ddr4_adr[6]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports {c0_ddr4_adr[7]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H26 [get_ports {c0_ddr4_adr[8]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E25 [get_ports {c0_ddr4_adr[9]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C24 [get_ports {c0_ddr4_adr[10]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {c0_ddr4_adr[11]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B25 [get_ports {c0_ddr4_adr[12]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E26 [get_ports {c0_ddr4_adr[13]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D24 [get_ports {c0_ddr4_adr[14]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J23 [get_ports {c0_ddr4_adr[15]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports {c0_ddr4_adr[16]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports {c0_ddr4_dqs_t[0]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports {c0_ddr4_dqs_c[0]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports {c0_ddr4_dqs_t[1]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {c0_ddr4_dqs_c[1]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {c0_ddr4_dqs_t[2]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports {c0_ddr4_dqs_c[2]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports {c0_ddr4_dqs_t[3]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {c0_ddr4_dqs_c[3]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22 [get_ports {c0_ddr4_dm_n[0]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports {c0_ddr4_dm_n[1]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {c0_ddr4_dm_n[2]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {c0_ddr4_dm_n[3]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C23 [get_ports {c0_ddr4_dq[0]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports {c0_ddr4_dq[1]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A24 [get_ports {c0_ddr4_dq[2]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C22 [get_ports {c0_ddr4_dq[3]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B24 [get_ports {c0_ddr4_dq[4]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {c0_ddr4_dq[5]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A25 [get_ports {c0_ddr4_dq[6]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E21 [get_ports {c0_ddr4_dq[7]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports {c0_ddr4_dq[8]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {c0_ddr4_dq[9]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {c0_ddr4_dq[10]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {c0_ddr4_dq[11]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {c0_ddr4_dq[12]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports {c0_ddr4_dq[13]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {c0_ddr4_dq[14]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {c0_ddr4_dq[15]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {c0_ddr4_dq[16]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports {c0_ddr4_dq[17]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports {c0_ddr4_dq[18]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {c0_ddr4_dq[19]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G21 [get_ports {c0_ddr4_dq[20]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports {c0_ddr4_dq[21]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {c0_ddr4_dq[22]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {c0_ddr4_dq[23]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {c0_ddr4_dq[24]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports {c0_ddr4_dq[25]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {c0_ddr4_dq[26]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {c0_ddr4_dq[27]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {c0_ddr4_dq[28]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports {c0_ddr4_dq[29]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {c0_ddr4_dq[30]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports {c0_ddr4_dq[31]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports sd_clk]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B12 [get_ports sd_cmd]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {sd_data[0]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {sd_data[1]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {sd_data[2]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports {sd_data[3]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC14 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC13 [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list andromeda_i/ddr4_0/inst/u_ddr4_infrastructure/u_bufg_divClk_0]]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 256 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[0]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[1]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[2]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[3]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[4]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[5]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[6]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[7]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[8]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[9]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[10]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[11]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[12]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[13]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[14]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[15]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[16]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[17]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[18]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[19]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[20]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[21]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[22]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[23]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[24]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[25]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[26]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[27]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[28]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[29]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[30]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[31]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[32]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[33]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[34]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[35]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[36]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[37]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[38]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[39]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[40]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[41]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[42]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[43]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[44]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[45]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[46]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[47]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[48]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[49]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[50]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[51]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[52]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[53]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[54]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[55]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[56]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[57]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[58]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[59]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[60]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[61]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[62]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[63]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[64]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[65]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[66]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[67]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[68]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[69]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[70]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[71]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[72]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[73]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[74]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[75]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[76]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[77]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[78]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[79]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[80]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[81]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[82]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[83]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[84]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[85]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[86]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[87]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[88]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[89]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[90]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[91]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[92]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[93]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[94]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[95]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[96]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[97]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[98]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[99]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[100]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[101]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[102]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[103]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[104]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[105]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[106]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[107]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[108]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[109]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[110]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[111]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[112]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[113]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[114]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[115]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[116]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[117]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[118]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[119]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[120]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[121]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[122]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[123]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[124]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[125]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[126]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[127]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[128]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[129]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[130]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[131]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[132]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[133]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[134]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[135]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[136]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[137]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[138]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[139]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[140]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[141]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[142]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[143]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[144]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[145]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[146]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[147]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[148]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[149]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[150]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[151]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[152]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[153]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[154]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[155]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[156]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[157]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[158]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[159]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[160]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[161]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[162]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[163]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[164]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[165]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[166]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[167]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[168]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[169]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[170]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[171]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[172]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[173]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[174]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[175]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[176]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[177]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[178]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[179]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[180]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[181]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[182]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[183]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[184]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[185]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[186]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[187]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[188]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[189]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[190]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[191]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[192]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[193]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[194]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[195]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[196]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[197]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[198]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[199]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[200]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[201]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[202]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[203]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[204]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[205]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[206]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[207]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[208]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[209]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[210]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[211]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[212]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[213]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[214]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[215]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[216]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[217]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[218]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[219]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[220]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[221]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[222]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[223]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[224]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[225]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[226]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[227]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[228]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[229]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[230]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[231]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[232]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[233]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[234]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[235]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[236]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[237]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[238]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[239]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[240]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[241]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[242]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[243]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[244]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[245]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[246]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[247]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[248]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[249]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[250]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[251]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[252]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[253]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[254]} {andromeda_i/axi_dpe_0/inst/dpe_dout_debug[255]}]]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list andromeda_i/axi_dpe_0/inst/dpe_en]]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list andromeda_i/axi_dpe_0/inst/dpe_start]]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
